AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: delay-media

Globals:
  Function:
    Timeout: 5
    Runtime: python3.9
    Architectures: [ x86_64 ]
    Handler: app.lambda_handler
    Layers: [ !Ref DependenciesLayer ]
    Environment:
      Variables:
        StageName: !Ref StageName
        EVENT_BUS: !Ref EventBus

Parameters:
  StageName:
    Type: String
    Default: default
  EventBus:
    Type: String
    Default: default

Resources:

  # Functions

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delete/
      Tracing: Active

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/upload/
      Tracing: Active

  # Dependencies

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: delay-media-dependencies${StageName}
      ContentUri: dependencies
    Metadata:
      BuildMethod: python3.9

  # Storage bucket

  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: delay-media-storage-${StageName}


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
